version: "3.4"

services:
  frontend:
    build: ./frontend
    container_name: vue-frontend
    expose:
      - "8080"
    volumes:
      - ./frontend:/frontend
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"

  backend:
    container_name: express-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      APP_PORT: 3003
      VUE_APP_ORIGIN: "http://localhost:8080"
      DB_HOST: "database"
      DB_PORT: 5434
      DB_DATABASE: "resource_app"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      APP_HOST: "0.0.0.0"
    ports:
      - 3003:3003
    tty: true

  database:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: "Asia/Tokyo"
    ports:
      - 5434:5434

volumes:
  postgres_data: